#!/bin/sh -efu

cd "$(dirname $(realpath $0))"
. ./jekyll-common.sh

podman run --user 0 -p 4000:4000 -it --rm --userns=keep-id:uid=1000,gid=1000 -v "$PWD:/srv/jekyll:Z" "jekyll/builder:$JEKYLL_VERSION" jekyll serve
